### ISSUE TITLE
Parameter file

### ISSUE THREAD

**Issue by kareefardi** [The-OpenROAD-Project/TritonRoute#12]
Hello,

When providing a parameter file that lists, `def`, `lef`, `guide`, and `output`. The program terminates and outputs this error message:
> "Error reading param file!!!

I believe that's related to: https://github.com/The-OpenROAD-Project/TritonRoute/blob/cd611a7a31588d331ac89ea5c80591eda533403b/src/main.cpp#L68

Edit:
I forgot to mention that passing these parameters as command line arguments, the program runs successfully.

Thanks

**Comment by bangqixu** [comment]
Thanks for the feedback. The parameter file is not officially supported and users are recommended to use command line options instead.
