### ISSUE TITLE
Linking fail while building the project

### ISSUE THREAD

**Issue by diweshibm** [The-OpenROAD-Project/TritonRoute#15]
Hi, 
I just started working on my set up, and might be doing something wrong. I am getting following error while building the project: 

  0%] Built target LefBisonTarget
[ 13%] Built target lef
[ 13%] Built target DefBisonTarget
[ 31%] Built target def
[ 52%] Built target flexroutelib
[ 53%] Linking CXX executable TritonRoute
ld: library not found for -lcrt0.o
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [TritonRoute] Error 1
make[1]: *** [CMakeFiles/TritonRoute.dir/all] Error 2
make: *** [all] Error 2

Please take a look and let me know what went wrong.

**Comment by bangqixu** [comment]
Please list and check your system / dependency requirement.

**Comment by diweshibm** [comment]
I am setting up in MacOS Catalina. I am building project in VS Code  ( version 1.41.1) terminal. Boost version : 1.71.0. zlib version : 1.2.11. Bison version: 3.5. Let me know if you are looking for any other details.

**Comment by bangqixu** [comment]
A quick google search indicates this has something to do with MacOS. I would suggest try on a CentOS machine as described in README.
