### ISSUE TITLE
Wrong variable for boost include dirs

### ISSUE THREAD

**Issue by killruana** [The-OpenROAD-Project/TritonRoute#23]
On the branch openroad, the [CMakeFiles.txt](https://github.com/The-OpenROAD-Project/TritonRoute/blob/dd6972fa70eaca54eebb744627beea0089e5474d/CMakeLists.txt#L170) use the nonexistent `Boost_INCLUDE_DIR` variable for defining boost include dirs.
The variable to use is `Boost_INCLUDE_DIRS`, cf the [documentation](https://cmake.org/cmake/help/v3.1/module/FindBoost.html).

**Comment by maliberty** [comment]
This is fixed in the latest integrated TR.
