### ISSUE TITLE
Pin Enclosure Problem

### ISSUE THREAD

**Issue by viyelesay** [The-OpenROAD-Project/TritonRoute#29]
First of all, thanks for this tool. I am using TritonRoute in another process technology. In my case, vias should be covered at least by enclosure amount in one direction. For example, if the track enters the via from south direction, the track must cover at least by the enclosure amount at the north direction. However, if the via is at the end of track, it is not covered properly. Any idea is welcome.

**Comment by rovinski** [comment]
You need to define vias in the LEF which satisfy enclosure rules by themselves, e.g. a cross shape:

![image](https://user-images.githubusercontent.com/3936698/88326918-8beef000-ccf4-11ea-872d-732875daa19c.png)

Most commercial libraries already have this.

**Comment by viyelesay** [comment]
Yes, I tried that, but than I have ap errors. It only worked  for very simple circuits.

**Comment by rovinski** [comment]
TritonRoute is not able to handle cells which have a dense pin clustering (e.g. cells with <= x1 drive strength). Try not to use those cells.

Other than that, I can't help you without at least a test case, screenshots, or log files.

**Comment by viyelesay** [comment]
If I edit the lef file and generate def file, via definitions are taken from the technology library during the import process to cadence. Since via definition on lef file and technology library are different, it results in drc errors. My quick solution is to add metal on the via locations directly on the def file as defined in the lef file. This solves drc problem. I think the best solution is during the path generation to cover entire via using metal layers as via definition in the lef file.
