### ISSUE TITLE
Tech Lef and Global parameter control

### ISSUE THREAD

**Issue by viyelesay** [The-OpenROAD-Project/TritonRoute#32]
I have added second lef option in TritonRoute to avoid merge operation. I have also added option to program global variables using param file. Please check the attached file. For backward compatibility, I made second lef optional.
[tech_lef.zip](https://github.com/The-OpenROAD-Project/TritonRoute/files/5119468/tech_lef.zip)

**Comment by maliberty** [comment]
mergeLef may merge more than two files together so this doesn't really replace it in a general way.  The direction is to move towards integrating TR into openroad and have it read from OpenDB directly.  That will eliminate this issue fully.  I'm going to close this as I don't think we will pursue this direction.
