### ISSUE TITLE
Missing header

### ISSUE THREAD

**Issue by dbellix** [The-OpenROAD-Project/TritonRoute#35]
Hi,
The following header are referenced in CMakeLists.txt but are non-existents:
- ${FLEXROUTE_HOME}/src/db/obj/frCMap.h

It is located at line 135. Without this header, it is not possible to install TritonRoute, but commenting that line does the job (Ubuntu 20.04)

**Comment by Ukuer** [comment]
did you build it on docker ?

**Comment by dbellix** [comment]
No i built it without docker. It works by commenting that line (I tried the AES with the nandgate45), but I don't know if in other cases frCMap header is called somehow.

**Comment by maliberty** [comment]
Fixed in the latest code (integrated TR in OpenRoad).
