### ISSUE TITLE
Timeout parameter not being honored

### ISSUE THREAD

**Issue by ayeung-fw** [The-OpenROAD-Project/TritonRoute#36]
Hi,

In the default OpenROAD flow, there is a parameter for timeout in the parameter file for TritonRoute:
timeout:2400

I don't think it is getting honored as the run time is still very long, like running overnight and still in 60th iteration. Also, I have tried changing the value to 1 and 60, but not much difference.

How can I get the tool to honor the timeout parameter? What unit is it in?
Is there a way to limit the number of DRC cleanup iterations like commercial EDA tools?

Thanks,
Adrian

**Comment by maliberty** [comment]
There is no timeout parameter in TR.
