### ISSUE TITLE
Failure to route

### ISSUE THREAD

**Issue by oharboe** [The-OpenROAD-Project/TritonRoute#5]
I have a design that fails to route:

Full log: [tritonoutput.txt](https://github.com/The-OpenROAD-Project/TritonRoute/files/3483395/tritonoutput.txt)

```
# TritonRoute 2>&1 ./TritonRoute.param    | tee tritonoutput.txt
[deleted]
cpu time = 00:00:01, elapsed time = 00:00:01, memory = 1302.48 (MB), peak = 1302.59 (MB)

start detail routing ...
start initial detail routing ...

Error: pin _249421_/B1 still does not have temp ap
```

**Comment by tajayi** [comment]
'still does not have temp ap' This error typically means something is off about the tracks specified in the DEF file (generated by verilog2def). If you are using nangate45 from the alpha-release please ensure 2 things:
1. User the latest flow/platforms/nangate45/tracks.info from commit 048f9ac2abfdf9959d7b2dc222c28367465d6dd9
2. Ensure that your floorplan is a multiple of the placement site. # x=0.19 y=1.4

**Comment by tajayi** [comment]
For clarification, the `DIE_AREA`, `CORE_AREA` have to be multiple of 0.19 in the x-direction and 1.4 in the y-direction

**Comment by oharboe** [comment]
I'm now trying: 
```
# These values must be multiples of placement site
# x=0.19 y=1.4
export DIE_AREA    = 0 0 900.22 901.6
export CORE_AREA   = 20.14 22.4 880.46 882
export CORE_WIDTH  = 860.32
export CORE_HEIGHT = 859.6
```

**Comment by tajayi** [comment]
I have no clue what that looks like. If you're willing to share your design again (privately if necessary), i can look into it.
