### ISSUE TITLE
TritonRoute report failure fail when it has violations in the 7th iteration

### ISSUE THREAD

**Issue by oharboe** [The-OpenROAD-Project/TritonRoute#6]
My design doesn't make it past TritonRoute, as I understand it. Presumably "number of violations = 4837" means that TritonRoute failed.

However, TritonRoute doesn't report this as a clear error in the alpha-release/flow. The exit code from the build script should be non-zero in the case of a TritonRoute failure.

```
start 7th optimization iteration ...
    completing 10% with 4921 violations
    elapsed time = 00:00:00, memory = 1721.97 (MB)
    completing 20% with 4921 violations
    elapsed time = 00:00:01, memory = 1721.97 (MB)
    completing 30% with 4919 violations
    elapsed time = 00:00:02, memory = 1721.97 (MB)
    completing 40% with 4879 violations
    elapsed time = 00:00:21, memory = 1721.97 (MB)
    completing 50% with 4867 violations
    elapsed time = 00:00:49, memory = 1721.97 (MB)
    completing 60% with 4859 violations
    elapsed time = 00:02:30, memory = 1721.97 (MB)
    completing 70% with 4859 violations
    elapsed time = 00:08:20, memory = 1721.97 (MB)
    completing 80% with 4841 violations
    elapsed time = 00:09:13, memory = 1721.97 (MB)
    completing 90% with 4841 violations
    elapsed time = 00:09:13, memory = 1721.97 (MB)
    completing 100% with 4837 violations
    elapsed time = 00:09:14, memory = 1721.97 (MB)
  number of violations = 4837
cpu time = 00:09:20, elapsed time = 00:09:20, memory = 1721.97 (MB), peak = 1721.97 (MB)
Error: DRC report file is not specified

complete detail routing
total wire length = 4049859 um
total wire length on LAYER metal1 = 67424 um
total wire length on LAYER metal2 = 1454174 um
total wire length on LAYER metal3 = 1865012 um
total wire length on LAYER metal4 = 467895 um
total wire length on LAYER metal5 = 129560 um
total wire length on LAYER metal6 = 64623 um
total wire length on LAYER metal7 = 475 um
total wire length on LAYER metal8 = 692 um
total wire length on LAYER metal9 = 0 um
total wire length on LAYER metal10 = 0 um
total number of vias = 1315955
up-via summary (total 1315955):

------------------
 metal1     624436
 metal2     622358
 metal3      54980
 metal4       9485
 metal5       4548
 metal6        110
 metal7         38
 metal8          0
 metal9          0
------------------
           1315955

cpu time = 02:11:43, elapsed time = 02:11:43, memory = 1721.97 (MB), peak = 1721.97 (MB)

post processing ...

post processing ...

Runtime taken (hrt): 8167.99
cp results/nangate45/AptosAvalonMMSlave/4_cts.v results/nangate45/AptosAvalonMMSlave/5_route.v
cp results/nangate45/AptosAvalonMMSlave/2_floorplan.sdc results/nangate45/AptosAvalonMMSlave/3_place.sdc
cp results/nangate45/AptosAvalonMMSlave/3_place.sdc results/nangate45/AptosAvalonMMSlave/4_cts.sdc
cp results/nangate45/AptosAvalonMMSlave/4_cts.sdc results/nangate45/AptosAvalonMMSlave/5_route.sdc
[root@af531be742d5 data]# 

```

**Comment by tajayi** [comment]
Typically, tools should return a non-zero exit code when there is a failure. I believe automated routing is one of a few cases where it is debatable whether the tool should return zero when there are DRC violations. I believe TritonRout is exiting appropriately in this case, however, a separate issue can be addressing the quality of results.

Most routing tools/commands (including commercial) don't throw an error if there are potentially violations in the design. Also, most tools don't do a full-fledged DRC during routing. This is a subsequent step in the flow.

Routing is a "best-effort" task aims to be DRC clean but this is not always attainable. It is not uncommon for routing to complete successfully with a handfull of DRCs that the user has to manually fix (or adjust the design to workaround persistent DRCs).

The violations reported by TritonRoute are not necessarily equivalent to "actual" DRCs that may be reported by a validation tool. We are still exploring ways to perform and track DRCs metrics in the OpneROAD flow using open-source tools.

**Comment by oharboe** [comment]
This is very reminiscent of the problems I had with GeoScience software and exit code. If the reservoir simulator didn't converge, but otherwise worked fine, then was that a non-zero exit code?

The exit code just isn't adequate to describe the finer points of this situation.
