### ISSUE TITLE
src/io incomplete source?

### ISSUE THREAD

**Issue by speedbooster** [The-OpenROAD-Project/TritonRoute#8]
Hi
While **make install**ing TritonRoute, it gave me an error that it couldn't find the file **frGuidePrep.h**.
When i did **locate frGuidePrep.h**, it gave me a file in **PdnPinDumper/src/io/frGuidePrep.h**.

Also, the file **frPinPrep.h** in TritonRoute and PdnPinDumper is of different size. I think TritonRoute's **io** folder isn't up-to-date?

I tried to replace TritonRoute's **io** folder with that of PdnPinDumper (which had frGuidePrep.h and larger frPinPrep.h) but it gave error:

> [ 35%] Building CXX object CMakeFiles/TritonRoute.dir/src/io/frAPG.cpp.o
> /home/mbk/Downloads/openflow/TritonRoute/src/io/frAPG.cpp: In member function ‘void fr::APGWorker::main()’:
> /home/mbk/Downloads/openflow/TritonRoute/src/io/frAPG.cpp:239:22: error: ‘void fr::DRCWorker::main()’ is protected within this context
>        drcWorker.main();
>                       ^
> In file included from /home/mbk/Downloads/openflow/TritonRoute/src/io/frAPG.h:35,
>                  from /home/mbk/Downloads/openflow/TritonRoute/src/io/frAPG.cpp:29:
> /home/mbk/Downloads/openflow/TritonRoute/src/drc/frDRC.h:125:10: note: declared protected here
>      void main();
>           ^~~~
> /home/mbk/Downloads/openflow/TritonRoute/src/io/frAPG.cpp:295:22: error: ‘void fr::DRCWorker::main()’ is protected within this context
>        drcWorker.main();
>                       ^
> In file included from /home/mbk/Downloads/openflow/TritonRoute/src/io/frAPG.h:35,
>                  from /home/mbk/Downloads/openflow/TritonRoute/src/io/frAPG.cpp:29:
> /home/mbk/Downloads/openflow/TritonRoute/src/drc/frDRC.h:125:10: note: declared protected here
>      void main();
>           ^~~~
> make[2]: *** [CMakeFiles/TritonRoute.dir/build.make:141: CMakeFiles/TritonRoute.dir/src/io/frAPG.cpp.o] Error 1
> make[1]: *** [CMakeFiles/Makefile2:84: CMakeFiles/TritonRoute.dir/all] Error 2
> make: *** [Makefile:130: all] Error 2
>

**Comment by bangqixu** [comment]
Thanks for your feedback. We are able to compile following the instructions provided on a CentOS 7 machine with Boost 1.68.0 version. If you still have the compilation error, could you share your build environment information and the make log?

Regarding PdnPinDumper, PdnPinDumper is not a supported branch of TritonRoute.
